### ISSUE TITLE
gulp-minify-css deprecated

### ISSUE THREAD

**Issue by jonXmack** [lambdacreatives/tofino#108]
When running `npm install` I get the warning `npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.`

Thought you guys should be made aware.

**Comment by danimalweb** [comment]
Thanks. This might go away when I update the deps as per #110. I'll try and find the source, although its probably a nested dep that we might not be able to do anything about.

**Comment by danimalweb** [comment]
It's a nested dependency, we'll probably see more and more of these as the npm modules we use go stale. Let's hope the maintainers keep their packages up to date.

**Comment by danimalweb** [comment]
Use gulp-cssnano instead of gulp-minify-css.
