### ISSUE TITLE
Possible Theme Settings

### ISSUE THREAD

**Issue by danimalweb** [lambdacreatives/tofino#11]
Logo Upload
Email Address
Telephone Number
Menu Position - Left/Centre/Right
Menu Sticky - Yes/No

**Comment by mrchimp** [comment]
Social media accounts?

**Comment by mrchimp** [comment]
Sticky footer checkbox. See #19.

**Comment by mrchimp** [comment]
Registered company number
Registered company address
VAT number
Cookies Message

**Comment by danimalweb** [comment]
What are the use cases in which these would be used?
ᐧ

**Comment by mrchimp** [comment]
Company numbers would probably be put in the footer or other contact-type areas. Same with VAT. The cookies message would be (potentially) shown in a popup cookie message. See #25.
