### ISSUE TITLE
Webmaster role

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#12]
Editor role, extended with access to certain other things.

**Comment by mrchimp** [comment]
Or do we just use editor?

**Comment by danimalweb** [comment]
Good question. We'd need to look at the use cases we currently have to decide.

It's easy to add the editor role to edit theme options. 

Is there anything the editor role can't do that clients need?

**Comment by danimalweb** [comment]
We need to add the code to allow editors to edit theme options.
