### ISSUE TITLE
navwalker get_site_url causing issues with bedrock

### ISSUE THREAD

**Issue by jonXmack** [lambdacreatives/tofino#121]
In bedrock the site url is site.dev/wp/ but the home url is site.dev. Navwalker was adding /wp/ to second level nav items due to `get_site_url`,  I switched it out to `get_home_url` and it's now working as I'd like it to. Not sure if this is a tofino thing due to our specific build requirements, just thought it was worth mentioning.

**Comment by danimalweb** [comment]
Good find. Can you create a pull request for this change on the dev branch?

**Comment by danimalweb** [comment]
I can't find ```get_site_url``` in the nav walker. Can you confirm where this code is in the repo?

**Comment by jonXmack** [comment]
Hmm, odd. I wouldn't worry about it if you can't find it!
