### ISSUE TITLE
Make JS ajax request code modular ES6 with callbacks

### ISSUE THREAD

**Issue by danimalweb** [lambdacreatives/tofino#153]
So we can leave the library code (ajax-form.js) unmodified and do custom processing on a per form basis.

Template: https://github.com/umdjs/umd/blob/master/templates/returnExports.js

Add an init function to hook in the standard processing via a class, maybe `AjaxForm.init('.form-processor');` and then:

```
var my_form = new AjaxForm('form#foo');
my_form.addProcessort(function () {});
```

**Comment by mrchimp** [comment]
You don't need the `init()` line.

**Comment by danimalweb** [comment]
Make this a jQuery plugin.

**Comment by danimalweb** [comment]
Close PR has been merged.
