### ISSUE TITLE
sticky menu doesn't work properly if you refresh the page while already scrolled

### ISSUE THREAD

**Issue by jonXmack** [lambdacreatives/tofino#156]
Title is self explanatory really, if you refresh the page while scrolled `100px` for example, it'll set `stickyTop` to `100` meaning that the sticky menu only triggers once you've scrolled past this point. I threw this quick workaround in which definitely needs refining but is a good enough fix for me for now.

``` 
$(window).load(function() {
  if (stickyTop > 0) {
    $sticky.addClass('stuck');
    stickyTop = 0;
  }
});
```

**Comment by danimalweb** [comment]
Can you demo this issue for me next week when I'm in your office? Cheers.

**Comment by danimalweb** [comment]
I think this is an issue with the position sticky polyfill we are using which hasn't been updated in more than 6 months. Might be best to patch this on a case by case basis or consider using another polyfill. Closing, re-open if it becomes a more of a problem and we can so something about it.
