### ISSUE TITLE
Dev Meeting - May 2016

### ISSUE THREAD

**Issue by danimalweb** [lambdacreatives/tofino#158]
- [ ] WooCommerce integration
- [ ] Plugins (MailChimp, SendGrid, Stripe etc)
- [ ] Standard extras (Carousel, Pagination)
- [ ] Hidden extras (UnCSS, Critical CSS)
- [ ] Javascript via ES6
- [ ] Bootstrap / CSS framework
- [ ] Theme options (WP Customizer, Theme Tracker API)
- [ ] AjaxForm (Why, How etc)
- [ ] Build process gripes (Linting, Gulp, NPM)
- [ ] Deployment
- [ ] Documentation
- [ ] Yadda's open issues (#154, #155, #156)
- [ ] Bugfix releases

@mrchimp Add anything you want to talk about.

**Comment by mrchimp** [comment]
Bugfix releases

**Comment by jonXmack** [comment]
CSS Structure

**Comment by lesteak** [comment]
Actions from meeting

# Woocommerce
* @jonxmack to take ownership of stripped down woocommerce.scss and maintain it. Should not be imported into main.scss by default.
* PHP - Add core Woocommerce styles removal and only execute if woocomerce()
* Have a look at common hooks on Dolphin and Valery.
* @lesteak will supply these repos to @danimalweb who is going to look at this

# Plugins
* @danimalweb has made a bunch of plugins to do standard stuff (Mailchimp API requests, Stripe Payments etc...).
* He's going to add these to Tofino and they'll be controlled within the theme options.
* Could we list these somewhere please?

# Standard Extras
* @danimalweb to include his pagination function in the build

# Hidden Extras
* CriticalCSS. Yadda to have a play.
* @jonxmack send a link to @danimalweb of JS font pull

# Javascript via ES6
* @danimalweb to have a look at manually including JQuery workaround for Slick etc..
* workarounds required for unprepared plugins on Yadda wiki
* can we find a way of getting external dependencies to be ignored by js-lint @danimalweb

# Bootstrap / CSS
* @jonxmack to write a blog post about CSS tings

# Theme Options
* Make sure that Theme Tracker is set to disabled
* please find a way to add Tofino Theme version to infiniteWP @lesteak

# Ajaxform
* Let's develop a back end viewable database view of all submissions (wp_postmeta lookup)
* @danimalweb @mrchimp to discuss the technical particulars
* Let's make some moar dox (https://github.com/lambdacreatives/tofino/tree/dev/src/forms)

# Build process gripes
* remove bower from .travis.yml
* use .travis to test node versions
* keep Readme.md up to date with tested current node version (please test properly!)
* leaving a caret in front of certain tools like the linter is a bad idea mmkay (in package.json)

# Deployment
* Rocketeer, please investigate this further one and all @lesteak @jonxmack @mrchimp

# Bugfix and at least some testing on new releases!
* dreams of further .travis testing @danimalweb

**Comment by jonXmack** [comment]
Woocommerce CSS
https://github.com/lambdacreatives/tofino/pull/164

webfontloader
https://github.com/lambdacreatives/tofino/issues/165
