### ISSUE TITLE
@extend inside an @include causes problems

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#159]
`assets/styles/base/nav.scss`

    @include media-breakpoint-up(sm) {
      .menu-right {
        .navbar-nav {
          float: right;
          padding-right: 5px;
        }

        .dropdown-menu {
          @extend .dropdown-menu-right;
        }
      }
    }

This code is causing problems with the latest versions of Node. I've had to comment out the `@extend` line.

**Comment by danimalweb** [comment]
Replace with:

```
@include media-breakpoint-up(sm) {
  .menu-right {
    .navbar-nav {
      float: right;
      padding-right: 5px;
    }

    .dropdown-menu {
      right: 0;
      left: auto;
    }
  }
}
```
