### ISSUE TITLE
footer not loading, wp_footer related?

### ISSUE THREAD

**Issue by jonXmack** [lambdacreatives/tofino#160]
In 1.3 I've noticed that every now and then everything past the closing `</footer>` tag fails to load, which means the JS isn't running. Not sure if it's related to `wp_footer` or not but that's where it's ending. A page refresh then makes it work fine.

**Comment by danimalweb** [comment]
Can you check the Theme Tracker theme option is set to Disabled?

**Comment by jonXmack** [comment]
I'll update that now and let you know if the issue happens again.

**Comment by danimalweb** [comment]
Related PHP error message in log file:
```
[Thu Apr 28 08:17:01.727147 2016] [:error] [pid 17219] [client X.X.X.X:57943] [Theme Tracker API Error] A valid URL was not provided.
```

Related commit in the dev branch ced82ab68d This fix is in the dev branch and will be part of v1.4.0.

I'll ensure that theme tracking is set to disbaled by default and if the URL is invalid a or empty the script tag is still rendered.

cc: @lesteak
