### ISSUE TITLE
Include theme directory in JS

### ISSUE THREAD

**Issue by jonXmack** [lambdacreatives/tofino#168]
Every now and then we have to get an asset in JS, correct me if I'm wrong but there's no easy way to do it short of hardcoding it which is obviously not idea so adding something like `'themeDir' => get_template_directory_uri()` on `line 163` of `src/lib/assets.php` means in js you can use `tofinoJS.themeDir` to get the theme directory in `main.js`. 

The one thing I'm not sure of is the naming of it, but I'm sure we can work out something sensible.

**Comment by mrchimp** [comment]
Sounds good to me.

**Comment by danimalweb** [comment]
Sounds good to me. Please send a PR.
