### ISSUE TITLE
Add core Woocommerce styles removal and only execute if WooCom exists

### ISSUE THREAD

**Issue by danimalweb** [lambdacreatives/tofino#170]
From the dev meeting.

Use something like: ```if (class_exists('WooCommerce'))``` to check for WooComm and then remove default styles via a hook / filter?

Do you think we should have a dedicated woocommerce.php file in src / lib for all the WooCommerce related PHP?

**Comment by jonXmack** [comment]
Sounds ideal and @lesteak agrees. @mrchimp, thoughts?

**Comment by mrchimp** [comment]
+1

**Comment by lesteak** [comment]
yep, sounds good.

what about overwriting this file when pulling from upstream?

**Comment by jonXmack** [comment]
Git should be able to merge automatically since any changes to this file will be made within the conditional, I guess if it can't then it'll be a conflict and you'll have to fix it manually.

**Comment by danimalweb** [comment]
Is it possible to get this on to the dev branch soon?

**Comment by danimalweb** [comment]
Anything further on this or should I close it?

https://docs.woocommerce.com/document/disable-the-default-stylesheet/

**Comment by danimalweb** [comment]
Closing until next WooComm job comes up.
