### ISSUE TITLE
Add a body.load event

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#192]
One that calls the relevant routes in the same way that the document.ready action does.

**Comment by danimalweb** [comment]
Started a WIP commit for this. Just an idea. Can probably be cleaned up.

Commit: 679730fb5177bae73448702ebfd8a36f3aa5dc6f

**Comment by danimalweb** [comment]
FYI, I found some bugs in the routing which will be fixed in the dev soon. If your already using this you should replace the files when I've committed the updates.
