### ISSUE TITLE
Nonces on cached pages

### ISSUE THREAD

**Issue by danimalweb** [lambdacreatives/tofino#210]
Enable a toggle to enable / disable nonces? or update the README to state that forms that are processed by AjaxForm will not work if a static cache has been enabled, as the nonce value is cached and then rejected (expired) when a form is submitted.

Load the token via ajax?
Cookies?
Update Ajax Form with a new param to skip the nonce check globally or on a per form basis.

**Comment by mrchimp** [comment]
Documentation is one of Tofino's shortcomings. It's a lot easier for me and you to use as we know how it was built but I've watched others pick it up and there are definitely some bits which aren't obvious. Maybe we should make a documentation site, maybe using Tofino. I'm happy to write a bunch but you'd have to help out with the bits that you know better.

**Comment by danimalweb** [comment]
Sounds like a good idea. Can you ask your devs and outline any areas which are most lacking / unclear.

**Comment by danimalweb** [comment]
In addition to the updated general docs. As all the functions are doc blocked would exported copy of those in a clean format be of use?

**Comment by mrchimp** [comment]
Not sure the docblock export would be that useful tbh.

General setup info would be nice - where to put JS, how to use the shortcodes, how to pass variables to the JS. Tofino does a lot of useful things but if you don't know about them then they're pointless.

**Comment by mrchimp** [comment]
How/where to add additional custom theme-options (e.g. footer options, social links, international phone nums and addresses etc) in theme-options.php.

**Comment by danimalweb** [comment]
How to create new theme options in addition to the ones which already exist?

**Comment by mrchimp** [comment]
Yeah.

**Comment by mrchimp** [comment]
> In which file can you change the default responsive nav settings from xs to sm/md screens?
> 
> yougetme?

**Comment by danimalweb** [comment]
Probably nav.scss in styles/base.
ᐧ

**Comment by danimalweb** [comment]
Closing, generally pages with forms shouldn't be cached. It's up to the dev to remove the nonce they caching is required for pages with forms.
