### ISSUE TITLE
Nav item not being marked as active

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#23]
From Andrew. The active class doesn't get applied to menu items if you are viewing a blog sub-page or an ACF archive.

This may just be a Sage thing but it's something we should test. I'm not sure if the blog sub-page part of it is only needed if ACF is active. We might need to make a theme setting for this, or maybe detect if ACF is active.

Here is the fix so far.

    // If your blog isn't at '/blog', you'll need to change that part of the code.
    // Mark (highlight) custom post type parent as active item in Wordpress Navigation
    add_action('nav_menu_css_class', 'add_current_nav_class', 10, 2 );
    function add_current_nav_class($classes, $item) {
      // Getting the current post details
      global $post;

      // Get post ID, if nothing found set to NULL
      $id = ( isset( $post->ID ) ? get_the_ID() : NULL );

      // Checking if post ID exist...
      if (isset( $id )){
        // Getting the post type of the current post
        $current_post_type = get_post_type_object(get_post_type($post->ID));
        $current_post_type_slug = $current_post_type->rewrite['slug'];           

        // Getting the URL of the menu item
        $menu_slug = strtolower(trim($item->url));

        // If the menu item URL contains the current post types slug add the current-menu-item class
        if (strpos($menu_slug,$current_post_type_slug) !== false) {
          array_push($classes, 'active');
        } elseif(strpos($menu_slug,'/blog')){
          // Extra fix for blog subpages, and grouped results      
          if(is_single() || is_tag() || is_month() || is_category()){
            array_push($classes, 'active');
          }
        }
      }
      // Return the corrected set of classes to be added to the menu item
      return $classes;
    }

**Comment by danimalweb** [comment]
I'd like more info on this. From my understanding active classes are usually applied via the WP_NavWalker class. The above fix presumes that the theme is using permalinks and the permalink structure is being used in the standard way.

A fix for all post types regardless of permalinks is what we need.

For terminologies sake, what is "ACF Archive" and "blog sub-page"?

I think a demo site where we can illustrate and link to problems would help. I'll try and set one up that always pulls from the master branch.

**Comment by mrchimp** [comment]
Andrew has showed me a case where this happens - albeit in Sage. I can show you it next time we talk if you like. This may have already been fixed in Tofino.

**Comment by danimalweb** [comment]
We should have found this, if it was an issue. Re-open if anyone has more info to add.
