### ISSUE TITLE
Imagemin takes ages to install

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#24]
Is there anything we can do to improve this? Or is there anything better we can use?

**Comment by danimalweb** [comment]
```
npm install gulp-imagemin
```

My OSX <45 secs (16GB RAM Quad Core)
Debian VM <45 secs (1GB RAM Dual Core)
Yadda Vagrant (Ubuntu) 2mins 30 seconds (2GB RAM 1 Core)

All tested on my MacBook Pro.

What times are you getting?

**Comment by mrchimp** [comment]
Several minutes. That was on OSX and (IIRC) Yadda Vagrant too. Hmmm. It's definitely not just me. Mark and John had the same. I'll investigate more and leave the issue open for now. There's definitely an issue somewhere but I don't know if it's a problem in Tofino or even anything we can fix.

**Comment by mrchimp** [comment]
It was installing Sage on a Linode server that was being slow. I've compared Tofino and Sage and it may have been the imagemin-pngcrush npm library rather than gulp-imagemin that is slow.

**Comment by mrchimp** [comment]
Just did a new installation on a Yadda Vagrant install. Couple of things I've noticed. I also ran `npm install imagemin`, `npm install gulp-imagemin` and `npm install imagemin-pngquant` separately in a empty directory (and ran `npm cache clean` in between each one) and they all took a few seconds. But when I run `npm install` from Tofino (or Sage) I get something like the following:

    > jpegtran-bin@3.0.4 postinstall /var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
    > node lib/install.js

      ⚠ Couldn't execute the `/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
      ⚠ jpegtran pre-build test failed
      ℹ compiling from source
      ✖ Error: ./configure --disable-shared --prefix="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
    Command failed: /bin/sh -c ./configure --disable-shared --prefix="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor"
    configure: error: no nasm (Netwide Assembler) found

        at ChildProcess.exithandler (child_process.js:751:12)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)
        at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    npm WARN optional dep failed, continuing fsevents@1.0.1

    > optipng-bin@3.0.2 postinstall /var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
    > node lib/install.js

      ⚠ Couldn't execute the `/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng` binary. Make sure it has the right permissions.
      ⚠ optipng pre-build test failed
      ℹ compiling from source
      ✖ Error: ./configure --with-system-zlib --prefix="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
    Command failed: /bin/sh -c ./configure --with-system-zlib --prefix="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor"

        at ChildProcess.exithandler (child_process.js:751:12)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)
        at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

    > gifsicle@3.0.1 postinstall /var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
    > node lib/install.js

      ⚠ Couldn't execute the `/var/www/other/wp-content/themes/other/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` binary. Make sure it has the right permissions.
      ⚠ gifsicle pre-build test failed
      ℹ compiling from source
      ✔ gifsicle built successfully

    > pngquant-bin@3.0.0 postinstall /var/www/other/wp-content/themes/other/node_modules/imagemin-pngquant/node_modules/pngquant-bin
    > node lib/install.js

      ⚠ Couldn't execute the `/var/www/other/wp-content/themes/other/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary. Make sure it has the right permissions.
      ⚠ pngquant pre-build test failed
      ℹ compiling from source
      ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
        at ChildProcess.exithandler (child_process.js:751:12)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)
        at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by danimalweb** [comment]
Looks like your getting closer to the issue. I can confirm that this doesn't happen on OSX.

```
> optipng-bin@3.0.2 postinstall /Users/daniel/Private/web/tofino.local/public_html/wp-content/themes/tofino/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@3.0.4 postinstall /Users/daniel/Private/web/tofino.local/public_html/wp-content/themes/tofino/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@3.0.1 postinstall /Users/daniel/Private/web/tofino.local/public_html/wp-content/themes/tofino/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> pngquant-bin@3.0.0 postinstall /Users/daniel/Private/web/tofino.local/public_html/wp-content/themes/tofino/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
```

**Comment by danimalweb** [comment]
We're going to remove the npm install option from wp-install. NPM modules for development should be installed on the machine you are coding on (Client).

**Comment by mrchimp** [comment]
I just ran it on my work mac and it was nice and quick. Then I ran it on my VM and it was too. I'm gonna close this. We can re-open it if we find any more info but I don't think it's a problem with Tofino.
