### ISSUE TITLE
Add console.log check to gulp

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#29]
console.log can cause issues on IE if left in on production. We should check for this and show a warnign when gulping. Are there any other similar things we should be checking for?

**Comment by danimalweb** [comment]
JSHint has a blanket function to check for undefined variables via undef in .jshintrc. Theres nothing special to catch console.logs or alerts. We can allow console.logs and alerts and not raise a warning by setting devel : true. Checkout the jshintrc file in the repo.
