### ISSUE TITLE
Missing files should cause errors

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#30]
There may be some rational to this that I'm not seeing but I think missing dependencies should stop the compilation. We should use Vinyl/Gulp4/whatever to make this happen. And/or consider outputting a list of included files for easier debugging.

**Comment by danimalweb** [comment]
I've added gulp-debug which outputs the files passed in to src. This should give us extra visability of whats in the pipe. I have a possible solution for checking the files exist via https://nodejs.org/api/fs.html#fs_fs_stat_path_callback let's talk about it soon.

**Comment by danimalweb** [comment]
I've removed gulp-debug as its output was a bit spammy.

**Comment by danimalweb** [comment]
Decided that we will produce a fatal error if a file is missing.

**Comment by mrchimp** [comment]
I've made it show big red warning for each file that doesn't exist. We can't use `process.exit()` without making watch die and I can't work out how to exit the task. I think this should do for now. Gulp 4 should bring some improvements.
