### ISSUE TITLE
Add an icon (svg sprite) option to social links

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#34]

**Comment by mrchimp** [comment]
Once this is done we could add a simple `get_social_links` function which would output a list of all social links as links with svg icons.

**Comment by mrchimp** [comment]
As discussed... We can't extend the social links component. But we can sluggify the title/name, so let's do that instead.

**Comment by danimalweb** [comment]
Some useful info here: https://github.com/valendesigns/option-tree/issues/263

**Comment by danimalweb** [comment]
I think its best that we filter the list of default social media site that option tree provide and only return the ones we want to use. This way we shouldn't need to slugify the title/name as it will remain fixed, we can link it to an SVG sprite.
