### ISSUE TITLE
Third party scripts not being added

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#44]
I'm using the free version of [this](https://yithemes.com/themes/plugins/yith-woocommerce-ajax-search/) and the scripts aren't being added to the site. Works fine with the default theme, so I'm assuming it's a Tofino issue.

**Comment by danimalweb** [comment]
Could be something to do with the fact that were deregistering the jquery that comes with WordPress and we are using our own version via bower.

**Comment by danimalweb** [comment]
The jQuery we are including is a BS4 dependency.
