### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#45]
`assets/fonts/*` should be copied to `dist/fonts/*` as well as any fonts from Bootstrap.

We also need a `fonts.scss` file.

**Comment by danimalweb** [comment]
Yep, we should make a gulp task for this and include it in the main build script. 

BS4 doesn't ship with any fonts. Yay!

I've started to use the Web Font Loader on a test project and I'm considering using it in future projects.
https://github.com/typekit/webfontloader

Any thoughts on this?

**Comment by danimalweb** [comment]
Changes required added in commit referenced above.
