### ISSUE TITLE
Blank after install

### ISSUE THREAD

**Issue by yaddabristol** [lambdacreatives/tofino#46]
front-page.php / home.php needs to be manually created with header and footer after install. This may be a feature and not a bug. Jake seems unsure.

**Comment by danimalweb** [comment]
What method is being used for the install? 
Do you have a home page defined via the reading settings?

**Comment by yaddabristol** [comment]
I installed within bedrock using clone and no, i hadn't changed that which was a schoolboy error. sorted now

**Comment by yaddabristol** [comment]
just updated comment above as you closed that. sorry ^

**Comment by mrchimp** [comment]
Should latest posts be the default view though? We almost always use a custom page and template for the home page.

**Comment by danimalweb** [comment]
It might be a good idea to have a loop.php or similar in the templates folder. This could then be used as a partial in the home page or a blogs section etc.

Custom page templates are mostly the way to go.

**Comment by yaddabristol** [comment]
I can't actually think of an incidence of not using a custom page template. Perhaps the question is how accessible you want this to be for non-lambda / yadda

**Comment by yaddabristol** [comment]
it may be an idea to have a home.php in the default install as a fall back for the posts page as no posts page will work by default even if selected in the reading settings

**Comment by mrchimp** [comment]
I think we should definitely have `post.php` and probably `front-page.php` by default. I think requiring a bit of setup is fine as Tofino is designed to be built on, but having some mainly empty defaults in there is helpful.

**Comment by danimalweb** [comment]
What is ```post.php``` for? We have ```single.php``` which passes the ```post_type``` into the templates folder.

**Comment by mrchimp** [comment]
Ah ignore me, I'm getting confused. `Post.php` isn't a thing. We just need `home.php`.

**Comment by danimalweb** [comment]
I'll add a home.php pointing to the page template. This can then be customized.
