### ISSUE TITLE
Can we auto-fix linting errors?

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#50]
PHP Code Sniffer says it can. What about the JS and SCSS?

**Comment by danimalweb** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically

**Comment by danimalweb** [comment]
We can fix PHP using the new php:fix gulp task.

**Comment by danimalweb** [comment]
Maybe for JS: https://github.com/jshint/fixmyjs looks a little dated though.

**Comment by danimalweb** [comment]
That's a yes for PHP and JS. No for SCSS (nothing out there yet). I checked out FixMyJS and it seems stable enough. All these fix tasks to be used with caution anyway. Gulp task for scripts:fix coming soon.
