### ISSUE TITLE
comments.php needed?

### ISSUE THREAD

**Issue by yaddabristol** [lambdacreatives/tofino#56]
Notice: Theme without comments.php is deprecated since version 3.0 with no alternative available. Please include a comments.php template in your theme. in /var/www/lbs/web/wp/wp-includes/functions.php on line 3512

**Comment by yaddabristol** [comment]
Sage version here https://github.com/roots/sage/blob/master/templates/comments.php

**Comment by danimalweb** [comment]
Comments is something I rarely use and therefore intentionally left out. I also remove all references to comments the admin using my WP Clean plugin.

When I do add comments I use https://disqus.com/ which has a WP plugin.

Are you guys using comments on many of sites you make?

**Comment by yaddabristol** [comment]
like yourself, barely ever but i have just had to implement it on an "intra-site" which sits behind WP login anyway. I do agree about disqus. perhaps don't worry for now. if i need it, i can just lift it off Sage like i have this time

**Comment by danimalweb** [comment]
Ok great. We'll add comments.php to projects when needed and will not roll it in to this theme.
