### ISSUE TITLE
Extra white space for files that don't have issues in sass-lint

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#67]
This might be an issue with sass-lint itself.

**Comment by danimalweb** [comment]
https://github.com/sasstools/gulp-sass-lint/pull/8 and https://github.com/sasstools/gulp-sass-lint/issues/7

**Comment by danimalweb** [comment]
A pull request has been made for this to be fixed in sass-lint.

**Comment by mrchimp** [comment]
v1.1.0 was released last night!
