### ISSUE TITLE
Composer is looking in the wrong place for the nav walker

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#70]
This line in the autoload block needs removing:

    "vendor/twittem/wp-bootstrap-navwalker/wp_bootstrap_navwalker.php",

**Comment by danimalweb** [comment]
I'm been tweaking the nav walker in the composer.json file to try and get an issue with Daintree resolved.

My changes didn't actually help so I might roll back to pulling the nav walker from the real repo instead of my forked version.

**Comment by danimalweb** [comment]
I reverted my change, this should no longer be an issue. Next time I'll use a new branch to test changes.
