### ISSUE TITLE
SVG shortcode isn't as flexible as I thought

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#88]
The `shortcode_atts` function only allows the attributes defined in the first parameter. This means that you can't add in arbitrary attributes, such as `preserveAspectRatio`. The only way I can think to fix this would be to add a list of all potential attributes, and that ain't pretty.

**Comment by danimalweb** [comment]
Might not be pretty, but useful to add each one as we need it?

I've never actually used ```preserveAspectRatio```. I'd be interested to see how you are using it.

**Comment by mrchimp** [comment]
I use it all the time. I've done quite a few designs with svg backgrounds that need to stretch to fit the background...and they totally break without preserveAspectRatio.

**Comment by danimalweb** [comment]
Sounds like preserveAspectRatio would be a good addition. Pull request?
