### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#93]
We should have a checkbox in the backend that, when checked, shows a modal (possibly using ThickBox) on the backend that says something to the effect of "This site is currently in maintenance mode. Any changes that you make may be reverted or removed. We aren't responsible for any loss of work, time, effort, etc. Seriously."

**Comment by danimalweb** [comment]
Is it normal that this overlay is displayed on every page load when it is enabled?

**Comment by mrchimp** [comment]
Yep.

**Comment by mrchimp** [comment]
This should be cookied until session expires. When it's dismissed also show a normal wordpress message at the top of the screen.
